### ISSUE TITLE
Images using indexed color mode don't work

### ISSUE THREAD

**Issue by MilesFarber** [swift502/EquimercConverter#2]
Z:\Programs\EquimercConverter>py -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\miles\appdata\local\programs\python\python312\lib\site-packages (24.1)

Z:\Programs\EquimercConverter>py -m pip install -r requirements.txt
Requirement already satisfied: pillow==10.2.0 in c:\users\miles\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (10.2.0)
Requirement already satisfied: moderngl==5.10.0 in c:\users\miles\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (5.10.0)
Requirement already satisfied: numpy==1.26.4 in c:\users\miles\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: glcontext<3,>=2.5.0 in c:\users\miles\appdata\local\programs\python\python312\lib\site-packages (from moderngl==5.10.0->-r requirements.txt (line 2)) (2.5.0)

Z:\Programs\EquimercConverter>py convert.py equi.png merc.png m

Converting "equi.png" to mercator.
Saving Z:\Programs\EquimercConverter\merc.png
←[32mSuccess!←[0m

Z:\Programs\EquimercConverter>pause
Press any key to continue . . .

![equi](https://github.com/swift502/EquimercConverter/assets/24918282/fa3793a3-e24e-4ef0-979e-0a82623b29c7)
![merc](https://github.com/swift502/EquimercConverter/assets/24918282/1079c137-3024-4ab7-b7a3-c3252ce6c57a)

**Comment by swift502** [comment]
Hey! Sorry it doesn't work for you.

It seems like your source image is using indexed colors, and the converter can't handle that.
![image](https://github.com/swift502/EquimercConverter/assets/24359130/f3aa5ca1-cbf3-4a7a-82c3-85f584b60cc2)

I might try fixing it, but in the meantime just convert your source images to RGB and it should work fine. 👌

**Comment by swift502** [comment]
@MilesFarber Just committed https://github.com/swift502/EquimercConverter/commit/07ff88b1a44184f8ea96c3f2e3f064e37ecb70f4, which should fix this.

If you pull master and try again it should work. Let me know how it goes. 🙏

And thanks for the report.

**Comment by swift502** [comment]
Hi, I also just changed the CLI arguments to hopefully be less confusing.

I'm closing this for now but if you have any more issues feel free to reopen or create a new one. Again, thanks a lot!
