### ISSUE TITLE
GPU Rendering

### ISSUE THREAD

**Issue by FluxOnIt** [swift502/EquimercConverter#3]
I found a little bug (I think)

in the ../src/shaders/fragment_to_equirectangular.glsl file I had to change the following lines for me to work.

line 4:  uniform sampler2D textureSampler;
line 32: fragColor = texture(textureSampler, uv);

Before I could only render using my CPU.

This fix worked on my end.

Greetings

Oliver

**Comment by swift502** [comment]
Thanks for the report. 🙏

Do you remember what error message you were getting? I never had issues with this.

Edit: I see texture2D() was deprecated 12 years ago... lol. I'll change it.

**Comment by swift502** [comment]
Please let me know the error if you know, but regardless it should be fixed now, closing.

Thanks again.

**Comment by FluxOnIt** [comment]
This was the error Message


Converting "input.png" to equirectangular.
Error: GLSL Compiler failed

fragment_shader
===============
ERROR: 0:32: Invalid call of undeclared identifier 'texture2D'
